### ISSUE TITLE
sc3nb runtime error

### ISSUE THREAD

**Issue by paulvickers** [interactive-sonification/sonecules#1]
Working through the first notebook, `sonecule-AUD-BasicAUD.ipynb`, and when I get to the cell that contains the line `aud1 = BasicAUD.from_df(df, sr=256, columns=7)` I get the following error:

````
ProcessTimeout                            Traceback (most recent call last)
File ~/.pyenv/versions/sonecules/lib/python3.11/site-packages/sc3nb/sclang.py:459, in SCLang.connect_to_server(self, server)
    458 try:  # if there are 'too many users' we failed. So the Exception is the successful case!
--> 459     self.read(expect="too many users", timeout=0.3, print_error=False)
    460 except ProcessTimeout:
````
I have installed sc3nb and I have SuperCollider installed on my system (macOS).

The output that precedes this error is:
````
Starting sclang process... [sclang | start reading ]
Done.
Registering OSC /return callback in sclang... Done.
Loading default sc3nb SynthDefs... Done.
Booting SuperCollider Server... 
SuperCollider Server port 57110 already used.
Trying to connect.
Done.
ERROR: unable to receive /return message from sclang
sclang output: (also see console) 

sc3> r['callback'].value("NetAddr.langPort", "127.0.0.1", 57142);
-> 57121
sc3> Requested notification messages from server 'sc3nb_remote'
sc3nb_remote - already registered with clientID 0.
sc3nb_remote - handling login request though already registered - 
This seems to be a login after a loss of network contact - 
- reconnected with the same clientID as before, so probably all is well.
````

Any ideas?

**Comment by paulvickers** [comment]
UPDATE: I looked at the sc3nb issues page and saw there is a problem with using Python 3.11. So, I switched to 3.9.1 and it seems to be working fine now. Might be worth noting this on the README?

**Comment by dreinsch** [comment]
I am glad you were able to find the sc3nb issue (https://github.com/interactive-sonification/sc3nb/issues/18) and a solution. We are currently looking into this problem and hopefully fix it soon.

**Comment by dreinsch** [comment]
Fixed upstream issue (https://github.com/interactive-sonification/sc3nb/issues/18).
